project_id = "bacvqrkibxzabhufxrtf"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[functions.send-confirmation-email]
verify_jwt = false

[functions.auth-hook]
verify_jwt = false