// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zygjzfaiejhfhmdnqblz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5Z2p6ZmFpZWpoZmhtZG5xYmx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMDg5MDUsImV4cCI6MjA2MDc4NDkwNX0.KlOZmlk1qv9Jw30Z3WKQyhN9yPge4ESQtJSkfarlqes";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);